version: "3.7"

services:
   item-db:
      image: mongo:3
      volumes:
         - app-db:/data/db
      restart: on-failure

   item-app:
      image: ghcr.io/vickywerenfridus/item-app:v1
      ports:
         - 80:8080
      restart: on-failure
volumes:
   app-db:
